### ISSUE TITLE
Add a method to send events back into the event channel

### ISSUE THREAD

**Issue by gha** [tomponline/fsclient#9]
Now that the event channel is no longer exposed outside the package, can we add a `SentInternalEvent` method to send user defined events into the event channel.

Example usage:

```go
event := make(map[string]string)
event["Unique-ID"] = legUUID
event["Event-Name"] = "CHANNEL_HANGUP_COMPLETE"
event["Event-Date-Timestamp"] = strconv.Itoa(int(time.Now().Unix() * 1000000))
event["Hangup-Cause"] = "UNKNOWN"
event["variable_sip_hangup_disposition"] = "unknown"
fs.SendInternalEvent(event)
```

**Comment by tomponline** [comment]
Sounds good @gha. It will need to implement the new slice buffer.

**Comment by jarisoft** [comment]
@tomponline, @gha I might look a bit lazy but isn't it enough to just call `deliverEvent(event)` or am I missing something?

```go
func (client *Client) SendInternalEvent(event map[string]string) {
    client.deliverEvent(event)
}
```

**Comment by tomponline** [comment]
@jarisoft that should work just fine :)

**Comment by jarisoft** [comment]
Thank you @tomponline for that feedback... I tried to push into your repository but get an permission error
```
ERROR: Permission to tomponline/fsclient.git denied to jarisoft.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tomponline** [comment]
@jarisoft try again now...

**Comment by jarisoft** [comment]
@tomponline thank you. That worked.

**Comment by tomponline** [comment]
@jarisoft can you put in a PR so I can merge please. Ta
